{% set name = "scikit-fem" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b138b7fa636a0ba0a4fcde01ffdf37f7e2efa9ea61ae8adcc331c856d7774eb4

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - meshio >=4.0.4
    - numpy
    - python >=3.6
    - scipy

test:
  imports:
    - skfem
    - skfem.assembly
    - skfem.assembly.basis
    - skfem.assembly.form
    - skfem.element
    - skfem.element.element_hex
    - skfem.element.element_line
    - skfem.element.element_quad
    - skfem.element.element_tet
    - skfem.element.element_tri
    - skfem.importers
    - skfem.mapping
    - skfem.mesh
    - skfem.mesh.mesh2d
    - skfem.mesh.mesh3d
    - skfem.models
    - skfem.visuals

about:
  home: https://github.com/kinnala/scikit-fem
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Simple finite element assemblers
  doc_url: https://kinnala.github.io/scikit-fem-docs
  dev_url: https://github.com/kinnala/scikit-fem

extra:
  recipe-maintainers:
    - kinnala
    - tlestang
