{% set name = "scikit-fem" %}
{% set version = "10.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f226155f75cf04feb77f5bdc4cba33cc7245b4e2f966047415559e5b4f64aa21

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - meshio >=4.0.4
    - numpy
    - python >=3.7
    - scipy
    - matplotlib

test:
  imports:
    - skfem
    - skfem.assembly
    - skfem.assembly.basis
    - skfem.assembly.form
    - skfem.element
    - skfem.element.element_hex
    - skfem.element.element_line
    - skfem.element.element_quad
    - skfem.element.element_tet
    - skfem.element.element_tri
    - skfem.io
    - skfem.mapping
    - skfem.mesh
    - skfem.models
    - skfem.visuals

about:
  home: https://github.com/kinnala/scikit-fem
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simple finite element assemblers
  doc_url: https://kinnala.github.io/scikit-fem-docs
  dev_url: https://github.com/kinnala/scikit-fem

extra:
  recipe-maintainers:
    - kinnala
