{% set name = "scikit-fem" %}
{% set version = "12.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2e68398c4b37314626ea735a508fc47a718ee578e51126b99a264a7d8395ec81

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit
  run:
    - meshio >=4.0.4
    - numpy
    - python >={{ python_min }}
    - scipy
    - matplotlib

test:
  requires:
    - python {{ python_min }}
  imports:
    - skfem
    - skfem.assembly
    - skfem.assembly.basis
    - skfem.assembly.form
    - skfem.element
    - skfem.element.element_hex
    - skfem.element.element_line
    - skfem.element.element_quad
    - skfem.element.element_tet
    - skfem.element.element_tri
    - skfem.io
    - skfem.mapping
    - skfem.mesh
    - skfem.models
    - skfem.visuals

about:
  home: https://github.com/kinnala/scikit-fem
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simple finite element assemblers
  doc_url: https://kinnala.github.io/scikit-fem-docs
  dev_url: https://github.com/kinnala/scikit-fem

extra:
  recipe-maintainers:
    - kinnala
